os: osx
language: swift
osx_image: xcode10.2

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone X'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 42mm'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 4K (at 1080p)'

before_install:
  - bundle install
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - set -o pipefail
  - xcodebuild -scheme UserDefaultsStore -destination "$DESTINATION" $ACTION | xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash)
